# Generated by Django 5.2.4 on 2025-08-04 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '유저', 'verbose_name_plural': '유저 목록'},
        ),
    ]
