# Generated by Django 5.2.4 on 2025-08-05 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_user_managers_userfollowing_user_following'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfollowing',
            unique_together={('to_user', 'from_user')},
        ),
    ]
